### PR TITLE
feat(Config): Present `core.preferMoveItem` config

### PR DESCRIPTION
**Pull request by Ash258**
- [ ] Investigate parity with robocopy on nanocore

Initial work on archive installation on *nix/nanocore support

### CODE REVIEW

**Comment by Ash258** [comment]
Linux archive installation 🎉 🎉 

image

**Comment by Ash258** [comment]
Simple zip:

image

7zip:

image

**Comment by Ash258** [comment]
zstd works out of the box without monkey patching

image

**Comment by Ash258** [comment]
image

**Comment by Ash258** [comment]
Global installations:

image

**Comment by Ash258** [comment]
Almost first nanoserver docker image built using new native installed. Lessmsi is missing some dependencies (activescott/lessmsi#98):

image
image

**Comment by Ash258** [comment]
In general msi installations are doomed in nanoserver

image

**Comment by Ash258** [comment]
Check parity with vcredist-nanoserver-installer

**Comment by Ash258** [comment]
See if `-Force` will be needed in future

**Comment by Ash258** [comment]
7z should use the `!` in string and the slash should not matter on Windows

image
image

On *nix it has to be constant
image

**Comment by Ash258** [comment]
Tar.gz installation is fine.

image

**Comment by Dipsonmick** [comment]
Hello sir.. i need to learn more on how to install and configure Nanocore.. can you help me with that?

**Comment by Ash258** [comment]
Verification run 1 start

**Pull request merged**
